data:
    image_size: 64  
    channels: 3
    num_workers: 0
    train_data_dir: "./dataset/NH-HAZE/train/"  # path to directory of train data
    # test_data_dir: './dataset/URHI_2/test_1/'  # path to directory of test data
    test_data_dir: './dataset/NH-HAZE/test/'  # path to directory of test data
    test_save_dir: '.dataset/NH-HAZE/conclusion_NH_415/'   # path to directory of saving restored data
    val_save_dir: './validation/validation_NH-HAZE/'
    # resize
    # train_data_dir: "./dataset/more_color_orgin_resize/train/"  # path to directory of train data
    # test_data_dir: './dataset/more_color_orgin_resize/test/'  # path to directory of test data
    # test_save_dir: './dataset/more_color_orgin_resize/conclusion_use_RE_3000_1223_3150/'   # path to directory of saving restored data
    # val_save_dir: './validation/validation_D_Hazy_6000/'
    grid_r: 16
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: sigmoid  
    beta_start: 0.0001   
    beta_end: 0.02       
    num_diffusion_timesteps: 2000  

training:
    patch_n: 16   
    batch_size: 1
    n_epochs: 2010  
    n_iters: 2000000
    snapshot_freq: 10000  # model save frequency
    validation_freq: 10000
    # resume: 'pretrained_model/818/' # train
    # resume: 'pretrained_model/RESIDE_SOTS_outdoor_1016/' # train
    # resume: 'pretrained_model/O-HAZY_NTIRE_2018_1026/' # train
    # resume: 'models_Reside_sots_outdoor/2000.pth.tar' # train
    resume: 'models_NH_HAZE/2000.pth.tar' # train
    seed: 61  # random seed

sampling:
    batch_size: 1
    last_only: True
    sampling_timesteps: 25

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
